exec("./item_candle.cs");
exec("./item_flaregun.cs");
exec("./item_book.cs");
exec("./item_gem.cs");
exec("./item_radio.cs");
exec("./item_soda.cs");
exec("./item_rope.cs");
exec("./weapon_dagger.cs");
exec("./weapon_killers.cs");